# Generated by Django 5.1.1 on 2024-10-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the book', max_length=50)),
                ('author', models.CharField(help_text='Name of the book writer', max_length=20)),
                ('detail', models.TextField(help_text='Description of the book')),
            ],
        ),
    ]
